/* This file was auto-generated using RapydScript */
(function(){
bad_list = null;
try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  _$rapyd$_print("Test 1: Got an exception");
}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, TypeError)) {
    _$rapyd$_print("Test 2: Got an exception");
  } else {
    throw _$rapyd$_Exception;
  }

}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  e = _$rapyd$_Exception;
  _$rapyd$_print(("Test 3: Got an exception" + str(e)));
}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, TypeError)) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 4: Got an exception" + str(e)));
  } else {
    throw _$rapyd$_Exception;
  }

}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, FakeError)) {
    b = _$rapyd$_Exception;
    _$rapyd$_print(("Test 5: This is unexpected" + str(b)));
  } else if (isinstance(_$rapyd$_Exception, TypeError)) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 5: Got an exception" + str(e)));
  } else {
    _$rapyd$_print("Test 5: This is unexpected too");
  }

}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, FakeError)) {
    _$rapyd$_print("Test 6: This is unexpected");
  } else if (isinstance(_$rapyd$_Exception, TypeError)) {
    _$rapyd$_print("Test 6: Got an exception");
  } else {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 6: This is unexpected too" + str(e)));
  }

}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, TestError)) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 7: unexpected error" + str(e)));
  } else if (isinstance(_$rapyd$_Exception, TypeError)) {
    d = _$rapyd$_Exception;
    _$rapyd$_print(("Test 7: Step 1" + str(e)));
    try {
      bad_list.fake_call2();
    } catch(_$rapyd$_Exception) {
      if (isinstance(_$rapyd$_Exception, NestException)) {
        _$rapyd$_print("Test 7: unexpected error");
      } else {
        _$rapyd$_print("Test 7: Step 2");
        try {
          bad_list.another_fake_call();
        } catch(_$rapyd$_Exception) {
          if (isinstance(_$rapyd$_Exception, FakeException)) {
            _$rapyd$_print("Test 7: unexpected error");
          } else {
            c = _$rapyd$_Exception;
            _$rapyd$_print(("Test 7: Step 3" + str(c)));
          }

        }

      }

    }

  } else if (isinstance(_$rapyd$_Exception, FinalError)) {
    _$rapyd$_print("Test 7: unexpected error");
  } else {
    throw _$rapyd$_Exception;
  }

}

ExceptClass = function() {
  
};

ExceptClass.prototype.test_exceptions = (function() {
  var b, c, d, e;
  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    _$rapyd$_print("Test 8: Got an exception");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TypeError)) {
      _$rapyd$_print("Test 9: Got an exception");
    } else {
      throw _$rapyd$_Exception;
    }

  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 10: Got an exception" + str(e)));
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TypeError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 11: Got an exception" + str(e)));
    } else {
      throw _$rapyd$_Exception;
    }

  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, FakeError)) {
      b = _$rapyd$_Exception;
      _$rapyd$_print(("Test 12: This is unexpected" + str(b)));
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 12: Got an exception" + str(e)));
    } else {
      _$rapyd$_print("Test 12: This is unexpected too");
    }

  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, FakeError)) {
      _$rapyd$_print("Test 13: This is unexpected");
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      _$rapyd$_print("Test 13: Got an exception");
    } else {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 13: This is unexpected too" + str(e)));
    }

  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TestError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 14: unexpected error" + str(e)));
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      d = _$rapyd$_Exception;
      _$rapyd$_print(("Test 14: Step 1" + str(e)));
      try {
        bad_list.fake_call2();
      } catch(_$rapyd$_Exception) {
        if (isinstance(_$rapyd$_Exception, NestException)) {
          _$rapyd$_print("Test 14: unexpected error");
        } else {
          _$rapyd$_print("Test 14: Step 2");
          try {
            bad_list.another_fake_call();
          } catch(_$rapyd$_Exception) {
            if (isinstance(_$rapyd$_Exception, FakeException)) {
              _$rapyd$_print("Test 14: unexpected error");
            } else {
              c = _$rapyd$_Exception;
              _$rapyd$_print(("Test 14: Step 3" + str(c)));
            }

          }

        }

      }

    } else {
      throw _$rapyd$_Exception;
    }

  }

});
try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  _$rapyd$_print("Test 15: Got an exception");
} finally {
  _$rapyd$_print("Test 15: Finally");
}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, TypeError)) {
    _$rapyd$_print("Test 16: Got an exception");
  } else {
    throw _$rapyd$_Exception;
  }

} finally {
  _$rapyd$_print("Test 16: Finally");
}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  e = _$rapyd$_Exception;
  _$rapyd$_print(("Test 17: Got an exception" + str(e)));
} finally {
  _$rapyd$_print("Test 17: Finally");
}

try {
  bad_list.fake_call();
} catch(_$rapyd$_Exception) {
  if (isinstance(_$rapyd$_Exception, TypeError)) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 18: Got an exception" + str(e)));
  } else {
    throw _$rapyd$_Exception;
  }

} finally {
  _$rapyd$_print("Test 18: Finally");
}

ExceptFinallyClass = function() {
  
};

ExceptFinallyClass.prototype.test_exceptions = (function() {
  var b, c, d, e;
  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    _$rapyd$_print("Test 19: Got an exception");
  } finally {
    _$rapyd$_print("Test 19: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TypeError)) {
      _$rapyd$_print("Test 20: Got an exception");
    } else {
      throw _$rapyd$_Exception;
    }

  } finally {
    _$rapyd$_print("Test 20: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    e = _$rapyd$_Exception;
    _$rapyd$_print(("Test 21: Got an exception" + str(e)));
  } finally {
    _$rapyd$_print("Test 21: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TypeError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 22: Got an exception" + str(e)));
    } else {
      throw _$rapyd$_Exception;
    }

  } finally {
    _$rapyd$_print("Test 22: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, FakeError)) {
      b = _$rapyd$_Exception;
      _$rapyd$_print(("Test 23: This is unexpected" + str(b)));
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 23: Got an exception" + str(e)));
    } else {
      _$rapyd$_print("Test 23: This is unexpected too");
    }

  } finally {
    _$rapyd$_print("Test 23: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, FakeError)) {
      _$rapyd$_print("Test 24: This is unexpected");
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      _$rapyd$_print("Test 24: Got an exception");
    } else {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 24: This is unexpected too" + str(e)));
    }

  } finally {
    _$rapyd$_print("Test 24: Finally");
  }

  try {
    bad_list.fake_call();
  } catch(_$rapyd$_Exception) {
    if (isinstance(_$rapyd$_Exception, TestError)) {
      e = _$rapyd$_Exception;
      _$rapyd$_print(("Test 25: unexpected error" + str(e)));
    } else if (isinstance(_$rapyd$_Exception, TypeError)) {
      d = _$rapyd$_Exception;
      _$rapyd$_print(("Test 25: Step 1" + str(e)));
      try {
        bad_list.fake_call2();
      } catch(_$rapyd$_Exception) {
        if (isinstance(_$rapyd$_Exception, NestException)) {
          _$rapyd$_print("Test 25: unexpected error");
        } else {
          _$rapyd$_print("Test 25: Step 2");
          try {
            bad_list.another_fake_call();
          } catch(_$rapyd$_Exception) {
            if (isinstance(_$rapyd$_Exception, FakeException)) {
              _$rapyd$_print("Test 25: unexpected error");
            } else {
              c = _$rapyd$_Exception;
              _$rapyd$_print(("Test 25: Step 3" + str(c)));
            }

          } finally {
            _$rapyd$_print("Test 25: Finally A");
          }

        }

      }

    } else {
      throw _$rapyd$_Exception;
    }

  } finally {
    _$rapyd$_print("Test 25: Finally B");
  }

});
try {
  bad_list.fake_call();
} finally {
  _$rapyd$_print("Finally");
}

window.onload = (function() {
  var a;
  a = new ExceptClass();
  a.test_exceptions();
});

}());